import { scoreLead } from "./scoring";

const RAW = [
  {
    id: "demo-1",
    source: "Reddit",
    sub: "r/Nigeria",
    handle: "u/chukwuemeka_biz",
    excerpt: "My salon has been running for 3 years but I still have no website. Customers always ask if I have one. How do I even start getting one built?",
    region: "Nigeria",
    ageHours: 0.1,
    keyword: "no website",
    contact: { type: "reddit", url: "https://www.reddit.com/r/Nigeria/comments/1example/salon_needs_website/" },
    createdAt: new Date(Date.now() - 6 * 60000).toISOString(),
  },
  {
    id: "demo-2",
    source: "Twitter / X",
    handle: "@amaka_style_ng",
    excerpt: "Does anyone know an affordable web designer in Lagos? My fashion brand seriously needs an online presence. DM me or drop recommendations below",
    region: "Nigeria",
    ageHours: 0.2,
    keyword: "web designer Nigeria",
    contact: { type: "twitter", url: "https://x.com/amaka_style_ng" },
    createdAt: new Date(Date.now() - 14 * 60000).toISOString(),
  },
  {
    id: "demo-3",
    source: "LinkedIn",
    handle: "James Okonkwo - CEO LogiTrans Ltd",
    excerpt: "Looking for a reliable web development agency to rebuild our logistics company site. It is outdated and not mobile-friendly. Budget is moderate. Any referrals?",
    region: "Nigeria",
    ageHours: 0.4,
    keyword: "redesign my website",
    contact: { type: "linkedin", url: "https://www.linkedin.com/in/james-okonkwo-logitrans", email: "j.okonkwo@logitrans.ng" },
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: "demo-4",
    source: "Google Maps",
    handle: "Stellas Kitchen Abuja",
    excerpt: "Business listed on Google Maps with 47 reviews but NO website link found. Category: Restaurant. Phone number visible. High foot traffic estimated.",
    region: "Nigeria",
    ageHours: 0.6,
    keyword: "no website found",
    contact: { type: "phone", phone: "+2348020000000", url: "https://maps.google.com/?q=Stellas+Kitchen+Abuja" },
    createdAt: new Date(Date.now() - 36 * 60000).toISOString(),
  },
  {
    id: "demo-5",
    source: "Facebook Groups",
    sub: "SME Nigeria",
    handle: "David Mensah",
    excerpt: "I need someone to build a simple website for my import and export business. Want to start accepting international orders. Budget flexible. Ghana based but working across West Africa.",
    region: "International",
    ageHours: 1.2,
    keyword: "need a website",
    contact: { type: "facebook", url: "https://www.facebook.com/groups/sme.nigeria" },
    createdAt: new Date(Date.now() - 72 * 60000).toISOString(),
  },
  {
    id: "demo-6",
    source: "Twitter / X",
    handle: "@realestateabuja",
    excerpt: "Our real estate agency website is SO slow. Takes 8 seconds to load. We are definitely losing leads because of it. Who can help? Need urgent fix.",
    region: "Nigeria",
    ageHours: 2,
    keyword: "website slow losing leads",
    contact: { type: "twitter", url: "https://x.com/realestateabuja", email: "info@realestateabj.com" },
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: "demo-7",
    source: "LinkedIn",
    handle: "Sarah Mitchell - Marketing Manager",
    excerpt: "Our UK startup is looking for an experienced freelance web designer for a project based engagement. Remote friendly. Must have portfolio of ecommerce or SaaS sites. Budget 800 to 1500 GBP.",
    region: "International",
    ageHours: 3,
    keyword: "freelance web designer",
    contact: { type: "linkedin", url: "https://www.linkedin.com/in/sarah-mitchell-techflow", email: "s.mitchell@techflow.io" },
    createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: "demo-8",
    source: "Quora",
    handle: "Anonymous User",
    excerpt: "What is the best way to get a website for a small Nigerian business? I run a logistics company and I feel I am losing clients to competitors who have professional websites.",
    region: "Nigeria",
    ageHours: 5,
    keyword: "website for my business",
    contact: { type: "quora", url: "https://www.quora.com/What-is-the-best-way-to-get-a-website-for-a-small-Nigerian-business" },
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: "demo-9",
    source: "Nairaland",
    sub: "Business",
    handle: "Emeka_Ventures",
    excerpt: "Please I need a web designer that can build a school management website for my new private school in Enugu. Budget is 150k. Must include student portal and payment integration.",
    region: "Nigeria",
    ageHours: 6,
    keyword: "need a web developer",
    contact: { type: "nairaland", url: "https://www.nairaland.com/7654321/school-management-website-enugu", phone: "+2348030000000" },
    createdAt: new Date(Date.now() - 6 * 3600000).toISOString(),
  },
  {
    id: "demo-10",
    source: "Reddit",
    sub: "r/Entrepreneur",
    handle: "u/startup_founder_us",
    excerpt: "I just launched my SaaS product but my landing page looks awful. Conversions are terrible. Looking for a designer who can do a clean redesign as soon as possible. Budget around 500 USD.",
    region: "International",
    ageHours: 8,
    keyword: "redesign landing page",
    contact: { type: "reddit", url: "https://www.reddit.com/r/Entrepreneur/comments/1example/saas_landing_page_redesign/" },
    createdAt: new Date(Date.now() - 8 * 3600000).toISOString(),
  },
  {
    id: "demo-11",
    source: "TikTok",
    handle: "@nigerianbizowner",
    excerpt: "Somebody should please recommend a good web designer for me. I want to take my tailoring business online. I keep seeing my competitors getting orders from their websites and I am missing out.",
    region: "Nigeria",
    ageHours: 1,
    keyword: "web designer",
    contact: { type: "tiktok", url: "https://www.tiktok.com/@nigerianbizowner" },
    createdAt: new Date(Date.now() - 1 * 3600000).toISOString(),
  },
  {
    id: "demo-12",
    source: "Nairaland",
    sub: "Webmasters",
    handle: "Lagos_Entrepreneur",
    excerpt: "I have been managing my catering business through WhatsApp only. I want a proper website with menu, booking form and WhatsApp button. Who can do this for a reasonable price in Lagos?",
    region: "Nigeria",
    ageHours: 4,
    keyword: "need a website",
    contact: { type: "nairaland", url: "https://www.nairaland.com/7654322/catering-business-website-lagos" },
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
];

export const DEMO_LEADS = RAW.map((l) => ({ ...l, score: scoreLead(l) }));

export function getRandomDemoLead(excludeIds) {
  const excl = excludeIds || [];
  const available = DEMO_LEADS.filter((l) => !excl.includes(l.id));
  if (!available.length) return null;
  const pick = available[Math.floor(Math.random() * available.length)];
  return {
    ...pick,
    id: "lead-" + Date.now() + "-" + Math.random().toString(36).slice(2, 6),
    createdAt: new Date().toISOString(),
    ageHours: Math.random() * 0.5,
  };
}
